---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name | quote }}
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: {{ .Values.deployment.name | quote }}
spec:
  {{- if .Values.deployment.ports }}
  ports:
  {{- toYaml .Values.deployment.ports | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.deployment.name | quote }}
