---
### Unit testing properties ###

auth-service:
  serverPort: 5000
  metricsPort: 5001
  metricsEndpoint: /metrics
  writeTimeoutSeconds: 10
  readTimeoutSeconds: 10
  issuer: info@thevpnbeast.com
  privateKey: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAqVXTwDGuM+87\npf9Oz632tZQ2j6jhkSoNEYHYlhTqBNMEP/N/6dqwtJzwKCBRGTC2N8+BUJbynx6x\nXMaCmjLQ+tRSYMfcwf0UoZWspl8uDCB/OY4NZweLXhFEuHMTV/u8M6bZhIIKu/9R\naCaLylJgXDXhTZ8iFMP5YTrHEFXxVowMVGNCYKrlWteJ7rTydJq/1Jo6muV2nXOX\nDSm5KrOJu2sVLpjXIeehupK5n7PrcK/Dr1RbisihvKiPu+14YEdrdfP7r4+KuVha\nx9PLB7YRR2S3ttuJckkAwEuevx1hPWn3rtspg8Zi6fu+65Llk7jTHPHexrMaXd8n\n7qydWMP7AgMBAAECggEBAK4bGTXP1NWhl0tnOq6lHYf7FeKstqiJv9+pd5ccIfBN\nxchsZoes9PWFcuHQ0UuYoR26l+o7wv2k8F7GAZra8JtMYX3Eejk0kZoIYDNy8kax\nrNhsUcQo3HeE3cQlj9DmTNcKMnkVt1MuC5Ast9DSWNk9228s72ckLun5hN2KFLCP\nudPM5jERYEwO0PoeUM9nY/8kx+JLhCXkvthwIlB1pBPZDfyFcG5qxT+dmTQI4Pg5\nNl/SFJHX2ALbcN0WStEoe/FuLT/08lZgb5VADpvH+KKvSaMihjlkxzwrJT0cAuss\nnbx9ub3x0VOjb5pRtbry/PhkLLwhiZD1Q37hXGltqoECgYEA/j4KxymxUdufgunC\nUPs5pDdJi10ZGlU3aDOTgF/7VtJuJk+KOat4/Q8zCzk+rL6+wThkUekBUpJO8YM8\nWNLMbVsPq7aD8uZjy1T9UQ2xClHvYRWVjPsRHJtgAzTp6FsYBJxBodpZB+6LCL35\nuChmLr1drdYXgLmF2bPkDWRgsEECgYEAwf5OrzTSbF3JXZYk2RkYouY7/ImcIgPm\n/6x+zDclQPwuJtT43kCsyVA7SRhGjX3RpLYcFk9Deem0RKAr6i7KJo4s0yAltdzA\nno089UcjJ068AVLCenOVm2BbJV6rywtPJJwmVpQMQrH0Xksif+hPGpxCIzQGXrQQ\nzdOQpOPm5TsCgYBHgygA8UdBISdy6VGQ+bky6aI0IxGmiIW3N5qrp1PJDhORjxnw\nMr0rYRUYeReZ+2UocDY3m/SVRzYRVLqquVBrCgwUXpgqwIcdcGB4ZgOARZ+xjSKt\nrwkXJNUS0dVhWA4fbdxALGySgJR29wjAtgxX5UfuV6Pwvz5ZB/KDmdJggQKBgDi5\nPpK2lEzBg67Mx0t/rhd70NCAAFpl37ak3pKiEU+WLXyHS5nZOWzH+/3cjkyzHIjY\nAxB27tkIAAENAKpCMjPh4LN/M+ege+YgkFF8Eohc2lZct6cMgxNismQT8ZG2Zdbj\nncY1FfyugjDMMXNLH049oI0gmjg42K0GjsXYKdyfAoGAV1dDKrA07CoJ46jtGFN1\n/clQG5Onm2bXSgwmEETvZyyir8yKKWkHXIojRbU9m8cuHwLbMtF1VeQ0VZcABMZB\n4/sg+YBXaaHewepJxwei20ewgj4SK/togka/kUfyXcKu8kHzOXIeX780EOPMferT\\n32LcrXUFphUzdX6ThYvWxyg=\\n-----END PRIVATE KEY-----"
  publicKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwKlV08AxrjPvO6X/Ts+t\n9rWUNo+o4ZEqDRGB2JYU6gTTBD/zf+nasLSc8CggURkwtjfPgVCW8p8esVzGgpoy\n0PrUUmDH3MH9FKGVrKZfLgwgfzmODWcHi14RRLhzE1f7vDOm2YSCCrv/UWgmi8pS\nYFw14U2fIhTD+WE6xxBV8VaMDFRjQmCq5VrXie608nSav9SaOprldp1zlw0puSqz\nibtrFS6Y1yHnobqSuZ+z63Cvw69UW4rIobyoj7vteGBHa3Xz+6+PirlYWsfTywe2\nEUdkt7bbiXJJAMBLnr8dYT1p967bKYPGYun7vuuS5ZO40xzx3sazGl3fJ+6snVjD\\n+wIDAQAB\\n-----END PUBLIC KEY-----"
  accessTokenValidInMinutes: 60
  refreshTokenValidInMinutes: 600
  encryptionServiceUrl: http://encryption-service:8085/encryption-controller/check
  dbUrl: spring:123asd456@tcp(vpnbeast-mysql:3306)/vpnbeast?parseTime=true&loc=Local
  dbDriver: mysql
  dbMaxOpenConn: 25
  dbMaxIdleConn: 25
  dbConnMaxLifetimeMin: 5
  healthCheckMaxTimeoutMin: 5
  healthPort: 5002
  healthEndpoint: /health
